spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: "jdbc:h2:mem:mydb"
    username: "root"
    password: "root"
    driver-class-name: org.h2.Driver

server:
  error:
    include-message: always
  port: 8086
